<?php

/**
 * hook_menu
 */
function goods_menu() {
  $items['goods'] = array(
    'title' => t('Список товаров'), 
    'page callback' => 'goods_list_datatable', 
    'access arguments' => array('access content'), 
    'type' => MENU_NORMAL_ITEM,
  );
  $items['goods/api/list'] = array(
    'title' => 'API/list', 
    'page callback' => 'goods_list_json', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );
  $items['goods/api/post'] = array(
    'title' => 'API/post', 
    'page callback' => 'goods_post', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Вывод списка товаров в DataTable c формой фильтрации
 */
function goods_list_datatable(){
    $attributes['datatable_options'] = array(
        'bFilter' => FALSE,
        'bInfo' => FALSE,
        'iDisplayLength' => 25,
        'bLengthChange' => FALSE,
        'bSearchable' => FALSE,
        'sDom' => 'tpr',
        'oLanguage' => array('sUrl' => 'http://cdn.datatables.net/plug-ins/a5734b29083/i18n/Russian.json'),
    );
    $header = array(
        array(
            'data' => t('Код'),
            'datatable_options' => array(
            'bSortable' => FALSE,
            ),
        ),
        array(
            'data' => t('Наименование'),
            'datatable_options' => array(
            'bSortable' => TRUE,
            ),
        ),
        array(
            'data' => t('Код категории'),
            'datatable_options' => array(
            'bSortable' => FALSE,
            'bVisible' => FALSE
            ),
        ),
        array(
            'data' => t('Категория'),
            'datatable_options' => array(
            'bSortable' => FALSE,
            ),
        ),
        array(
            'data' => t('Цена'),
            'datatable_options' => array(
            'bSortable' => TRUE,
            ),
        ),
    );
    drupal_add_js(drupal_get_path('module', 'goods') . '/js/scr.js');
    $out = form_filter();
    $out .= theme('datatable', array('header' => $header, 'rows' => goods_list(), 'attributes' => $attributes));
    $out .= modal_form(array('name'=>'AddGood', 'title'=>t('Новый товар'), 'button_text'=> t('Добавить')));
    $out .= modal_form(array('name'=>'EditGood', 'title'=>t('Редактирование товара'), 'button_text'=> t('Сохранить')));
    return  $out;    
}

/**
 * Реализация API/list список товаров JSON
 */
function goods_list_json(){
    drupal_json_output(goods_list());
    drupal_exit();
}

/**
 * Реализация API/post добавляет или изменяет товар
 */
function goods_post(){
    //drupal_json_output(goods_list());
    drupal_exit();
}

/**
 * Получение списка товаров из бд в соответствии с параметрами запроса GET
 */
function goods_list() {
    $query = db_select('goods', 'n');
    $query  ->join('category', 'c', 'n.category = c.id');
    $query  ->fields('n', array('id', 'name'))
            ->fields('c', array('id', 'name'))
            ->fields('n', array('price'));
    if (filter_has_var(INPUT_GET, 'name_substring')){
        $substr = db_like($_GET['name_substring']);
        $query  ->condition('n.name', '%' . $substr . '%', 'LIKE');
    }
    if (filter_has_var(INPUT_GET, 'name')){
        $name = db_like($_GET['name']);
        $query  ->condition('n.name', $name);
    }
    if (filter_has_var(INPUT_GET, 'id')){
        $id = db_like($_GET['id']);
        $query  ->condition('n.id', $id);
    }
    if (filter_has_var(INPUT_GET, 'notid')){
        $notid = db_like($_GET['notid']);
        $query  ->condition('n.id', $notid, '<>');
    }
    if (filter_has_var(INPUT_GET, 'category')){
        $cat = db_like($_GET['category']);
        if ($cat > 0) $query  ->condition('c.id', $cat);
    }
    return $query->orderBy('n.id')
            ->execute()    
            ->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * Получение категорий товаров из бд
 * $need_all = TRUE добавляет строку для всех категорий
 **/
function category_list($need_all = TRUE) {
    $query = db_select('category', 'c');
    $result = $query->fields('c', array('id', 'name'))
            ->orderBy('c.id')
            ->execute()    
            ->fetchAll(PDO::FETCH_ASSOC);
    if ($need_all) $cat['0']=t('Все категории');
    foreach ($result as $row)
    {	
        $cat[$row['id']]=$row['name'];
    }
    return $cat;
}

/**
 * Возвращает форму фильтров с кнопкой добавления нового товара
 */
function form_filter() {
    $form['name']=array(
        '#type'=>'textfield',
        '#size'=>30,
        '#id'=>'good_name_substring',
        '#description'=>t('Строка поиска'),
        '#attributes'=>array('placeholder'=>t('строка поиска'))
      );
    $form['category']=array(
        '#type'=>'select',
        '#suffix' => '&nbsp',
        '#title'=>' ',
        '#id'=>'good_category',
        '#options'=>category_list()
      );
    $form['button']=array(
        '#type'=>'button',
        '#attributes'=>array('onClick'=>'javascript:UpdateGoodsDataTable();'),       
        '#id'=>'set_goods_filter',
        '#value'=>t('Фильтр')
      );
    $form['submit']=array(
        '#type'=>'button',
        '#attributes'=>array('onClick'=>'javascript:OpenModalAddGood();'),       
        '#id'=>'goods_new',
        '#value'=>t('Добавить товар')
      );
    return '<form class="form-inline" id="goods_filter" action="javascript:void(0)">'.drupal_render($form).'</form><br/>';
}

/**
 * Возвращает модальную форму
 */
function modal_form($param){
    $out ='<div class="modal" id="Modal'.$param['name'].'"><div class="modal-dialog modal-dialog-centered" role="document">';
    $out.='<div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="'.$param['name'].'LongTitle">'.$param['title'].'</h5>';
    $out.='</div><div class="modal-body">'.modal_form_content($param['name']).'</div><div class="modal-footer">';
    $out.='<button type="button" class="btn btn-secondary" onclick="javascript:Modal'.$param['name'].'.style.display=\'none\';">'.t('Закрыть').'</button>';
    $out.='<button type="button" class="btn btn-primary" onclick="javascript:'.$param['name'].'();" id="'.$param['name'].'Button">'.$param['button_text'].'</button>';
    $out.='</div></div></div></div>';
    return $out;
}

/**
 * Возвращает содержимое модальной формы
 */
function modal_form_content($name){
    $form['category']=array(
        '#type'=>'select',
        '#title'=>' ',
        '#id'=>$name.'Category',
        '#options'=>category_list(FALSE)
    );
    $out = '<input type="text" class="form-control" id="'.$name.'Name" placeholder="Наименование">';
    $out.= '<div id="'.$name.'EmptyValidation" class="text-danger" style="display: none;">Наименование не может быть пустым.</div></form>';
    $out.= '<div id="'.$name.'ExistValidation" class="text-danger" style="display: none;">Товар с этим наименованием уже существует.</div></form>';
    $out.= drupal_render($form);
    $out.= '<input type="number" value="0" min="0" step="0.01" data-number-to-fixed="2" data-number-stepfactor="100" class="form-control currency" id="'.$name.'Price">';
    $out.= '<input type="hidden" id="'.$name.'Id" value="0" />';
    return $out;
}